### ISSUE TITLE
Succesful brute force attack

### ISSUE THREAD

**Issue by pk74** [KyberSwap/android-app#109]
I was successfully able to perform a brute force attack of seed.

**Comment by toidv** [comment]
@pk74 Could you explain more about the detail of the attack? How can you execute it and what is the result?. Currently, our wallet following BIP-39 so it means that the complexity of brute-force attack is the same as BIP-39 passphrase be cracked

**Comment by pk74** [comment]
The attack was very simple i generated few keys which were related to my
key!
It was a complex process.

But my start was simple
I had my key i just changed a word and i was in another account. I knew how
a key is created and the last word is checksum but some how it went right.
So this was the base to create few more keys.

If you want to simulate the same
Try creating keys with 1028 wordlist with a program to match the checksum.
You will succeed very easily.

**Comment by toidv** [comment]
@pk74 your process looks like creating a new wallet (it already built-in app), you have to try 2^128 times to generate a new key that collision with existing and the algorithm was proved safe
